### PR TITLE
Feature/float32array

### PR DESCRIPTION
**Pull request by gogoprog**
Put back and fixed float32array support for JavaScript target

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/haxe-starling/3)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/starling/utils/VertexData.hx, line 109 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn8Szr35gwdOzxUnIsd:-Kn8Szr35gwdOzxUnIse:btd3cno) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L109)):*
> ```Haxe
> 		
> 		#if js
> 			trace("FIX");
> ```

remove this comment

---

*[src/starling/utils/VertexData.hx, line 190 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn8Tb_3H80Ce1x8cLEE:-Kn8Tb_3H80Ce1x8cLEF:bbos71b) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L190)):*
> ```Haxe
> 		var rawDataLength:Int = rawData.length;
> 		
> 		mNumVertices += data.numVertices;
> ```

mNumVertices is already set in set_numVertices, you probably want to do `numVertices += data.numVertices;`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by crazyjul** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/starling/utils/VertexData.hx, line 109 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn8Szr35gwdOzxUnIsd:-Kn8hnh_-S_oA86FbOeH:bl2uvs4) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L109)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

remove this comment
</blockquote></details>

And fix it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/starling/utils/VertexData.hx, line 109 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn8Szr35gwdOzxUnIsd:-Kn9dabiCT2INfBvr-yP:b-7c1p99) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L109)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

And fix it
</blockquote></details>

woops yes, didn't see that ;) Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by rams3s** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/starling/utils/VertexData.hx, line 608 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn9rMi5f0iXANqm1-I9:-Kn9rMi5f0iXANqm1-IA:b-szdh3l) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L608)):*
> var newRawData = new Float32Array(length);
> 			if(mRawData != null) {
> 				for(i in 0...mRawData.length){
> 					newRawData[i] = mRawData[i];
> 				}
> 			}

might be worth optimizing this copy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by crazyjul** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/starling/utils/VertexData.hx, line 608 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn9rMi5f0iXANqm1-I9:-KnDgeesi1iwJ0zd9PnW:bph23xk) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L608)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> var newRawData = new Float32Array(length);
> 			if(mRawData != null) {
> 				for(i in 0...mRawData.length){
> 					newRawData[i] = mRawData[i];
> 				}
> 			}

might be worth optimizing this copy
</blockquote></details>

Maybe you could use Float32Array.set

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/starling/utils/VertexData.hx, line 109 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn8Szr35gwdOzxUnIsd:-KnDg82DPURq5LXHYDHh:b-896fix) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L109)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

woops yes, didn't see that ;) Thanks
</blockquote></details>

Done.

---

*[src/starling/utils/VertexData.hx, line 190 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn8Tb_3H80Ce1x8cLEE:-KnDg9vZCI5swvE0rmJy:b-896fix) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L190)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

mNumVertices is already set in set_numVertices, you probably want to do `numVertices += data.numVertices;`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-:-KnDqhuGogUuTWeh46nR:bnfp4nl)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/starling/utils/VertexData.hx, line 608 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn9rMi5f0iXANqm1-I9:-KnDqnqid77VwQ46KjFv:b-896fix) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L608)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Maybe you could use Float32Array.set
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/starling/utils/VertexData.hx, line 109 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn8Szr35gwdOzxUnIsd:-KnDq3JZqbRUUGJv3uzJ:b-mw3yuj) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L109)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

looks like subarray () second argument is an index and not a count. Negative values (such as the default -1) will not result in the whole array being cloned.

no need for clone.mRawData.fixed = true; anymore ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by gogoprog** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/starling/utils/VertexData.hx, line 109 at r1](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3#-Kn8Szr35gwdOzxUnIsd:-KnE12WG4voIzLcADKOu:b-7956vi) ([raw file](https://github.com/fishingcactus/haxe-starling/blob/1d9df813713d0930edcf647cad08f11871c00b98/src/starling/utils/VertexData.hx#L109)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

looks like subarray () second argument is an index and not a count. Negative values (such as the default -1) will not result in the whole array being cloned.

no need for clone.mRawData.fixed = true; anymore ?
</blockquote></details>

Fixed second argument,

.fixed doesn't exist on Float32Array

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/haxe-starling/3)*

**Pull request merged**
